version: "3"
services:
    mongo:
        container_name: mongo
        image: mongo
        restart: unless-stopped
        ports:
            - "7017:27017"
        volumes:
            - /home/kha/docker/mongo/data:/data/db
    wadu:
        container_name: wadu
        image: kaungkaung/wadu
        restart: unless-stopped
        links: 
            - mongo
        ports:
            - "3000:3000"